### ISSUE TITLE
Edit Raspberry Server settings

### ISSUE THREAD

**Issue by Patrick1610** [Ali1/Plex-Listen-and-WOL-for-Raspbian#2]
Hi, 

I have the script running for a while now, but would like to test some more with managed users in a home. For this I would like to edit some server settings on the Raspberry X Server. How can I start Plex so I can get into the settings? And what do I have to do afterwards to turn it back off and let the script run it from there on?

Regards, 
Patrick

**Comment by Ali1** [comment]
Hi

I've added a new section to the README "Running Plex Temporarily"
