### ISSUE TITLE
Too many symbolic links

### ISSUE THREAD

**Issue by dnrvn** [Ali1/Plex-Listen-and-WOL-for-Raspbian#3]
Hi, I am a total noob when it comes to linux, unix, etc. But I have a plex server that I have in a remote location and want to be able to wake it. Your project looked ideal, but I ran into the following error when running the following command:
sudo chmod 644 /lib/systemd/system/plexlistenandwol.service
The error says: chmod: cannot access '/lib/systemd/system/plexlistenandwol.service': Too many levels of symbolic links.

I am running a raspberry pi 2 B+, with fresh install of raspbian. Also I have successfully followed the steps up until this, and have set up PMS on my Pi, and I can see it in my account. 
  
Is there any way of automating the process for anyone that is linux-illiterate? Thanks in advance for your awesome project!

**Comment by Ali1** [comment]
I've just noticed a typo in the README on the step before that one. It was written like this:
```
sudo ln -s plexlistenandwol.service /lib/systemd/system/plexlistenandwol.servic e
```

Should be :
```
sudo ln -s plexlistenandwol.service /lib/systemd/system/plexlistenandwol.service
```
(fixed now)

Can you try the new steps?

**Comment by jerseyweeds** [comment]
Fully qualify the path then all is good
