### ISSUE TITLE
No config file found

### ISSUE THREAD

**Issue by dnrvn** [Ali1/Plex-Listen-and-WOL-for-Raspbian#5]
Hello,
I tried to setup again the service on a my old install of Raspbian jessie, and used the new code. 
But there are 2 issues: 
1) Again there are too many symbolic links when trying to do chmod 644 to the plexlistenandwol.service file
2) Trying to run the service, it cannot find the config.ini file. Yes, I have renamed it.

**Comment by dnrvn** [comment]
Issue was corrupted Raspbian installation. Reinstalled and works like a charm! I should pay you honestly, this code has made my family's plex experience so much easier and nicer, while saving me a lot of money on power bills and hdd wear! Kudos!

**Comment by Ali1** [comment]
Nice one glad to hear - I've transitioned to doing it in a different way which I think makes more sense - https://github.com/Ali1/PlexLocalWOL

But if it's working well for you, do carry on! 👍
